/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package reflection.app

import reflection.utilities.StringUtils

import org.apache.commons.text.WordUtils
import java.lang.Class;

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
    val widgetClass = Class.forName("reflection.app.Widget")
}
